### ISSUE TITLE
initial roadmap

### ISSUE THREAD

**Issue by lucaferranti** [lucaferranti/FuzzyLogic.jl#1]
## Basic types

- [x] Mamdami inference system
- [x] Sugeno inference system #5
- [x] Type-2 inference systems #18

## DSL

- [x] weighted rules #16
- [x] vector notation to avoid repetitive patterns #17

## Visualizations

- [x] plotting single variables
- [x] plotting inference system

## parsing

- [x] parse julia code
- [x] read matlab `.fis` files #15
- [x] fuzzy control language #13
- [x] fuzzy markup language #20

## Code generation

- [x] generate stand-alone julia code #21 
- [ ] generate stand-alone c code

## Others

- [x] fuzzy clustering https://github.com/lucaferranti/FuzzyLogic.jl/pull/11

## Documentation

- [x] mamdami tutorial
- [x] sugeno tutorial #5
- [x] type-2 tutorial
- [ ] control systems example
- [x] image processing application #6
- [x] API / internals documentation #5
- [x] contributing guideline polishing

## Infra

- [x] basic CI (run tests deploy docs)
- [x] literate integration for documentation

**Comment by lucaferranti** [comment]
with little more than 50% done, seems like a good moment for registering
